name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: SONAR_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build and test
        run: mvn clean verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: 3d41960ac9e1282b9e0c435f430366f7488e5081
        run: mvn sonar:sonar \
          -Dsonar.projectKey=PedroRiveraDuoc_skinsmask-products \
          -Dsonar.organization=pedroriveraduoc
